#!/bin/bash
echo ""
echo "Configuring index for custom attributes"
echo "---------------------------------------"
backendName="userStore"
${DS_APP}/bin/dsconfig  create-backend-index  --hostname "${svcURL_curr}" --port ${adminConnectorPort}  --bindDN "${rootUserDN}"  --bindPassword "${rootUserPassword}" --backend-name ${backendName} --index-name cif  --set index-type:equality  --trustAll  --no-prompt
${DS_APP}/bin/dsconfig  create-backend-index  --hostname "${svcURL_curr}" --port ${adminConnectorPort}  --bindDN "${rootUserDN}"  --bindPassword "${rootUserPassword}" --backend-name ${backendName} --index-name customerId  --set index-type:equality  --trustAll  --no-prompt
${DS_APP}/bin/dsconfig  create-backend-index  --hostname "${svcURL_curr}" --port ${adminConnectorPort}  --bindDN "${rootUserDN}"  --bindPassword "${rootUserPassword}" --backend-name ${backendName} --index-name ktp  --set index-type:equality  --trustAll  --no-prompt
echo "-- Done"
echo ""
echo "Configuring Plugin properties"
echo "-----------------------------"
${DS_APP}/bin/dsconfig  set-plugin-prop  --hostname "${svcURL_curr}"  --port ${adminConnectorPort}  --bindDN "${rootUserDN}" --bindPassword "${rootUserPassword}"  --plugin-name "UID Unique Attribute"  --add type:mail  --trustAll --set enabled:true --no-prompt
${DS_APP}/bin/dsconfig  set-plugin-prop  --hostname "${svcURL_curr}"  --port ${adminConnectorPort}  --bindDN "${rootUserDN}" --bindPassword "${rootUserPassword}"  --plugin-name "UID Unique Attribute"  --add type:cif  --trustAll --set enabled:true --no-prompt
${DS_APP}/bin/dsconfig  set-plugin-prop  --hostname "${svcURL_curr}"  --port ${adminConnectorPort}  --bindDN "${rootUserDN}" --bindPassword "${rootUserPassword}"  --plugin-name "UID Unique Attribute"  --add type:customerId  --trustAll --set enabled:true --no-prompt
${DS_APP}/bin/dsconfig  set-plugin-prop  --hostname "${svcURL_curr}"  --port ${adminConnectorPort}  --bindDN "${rootUserDN}" --bindPassword "${rootUserPassword}"  --plugin-name "UID Unique Attribute"  --add type:telephoneNumber --trustAll --set enabled:true --no-prompt
${DS_APP}/bin/dsconfig  set-plugin-prop  --hostname "${svcURL_curr}"  --port ${adminConnectorPort}  --bindDN "${rootUserDN}" --bindPassword "${rootUserPassword}"  --plugin-name "UID Unique Attribute"  --add type:ktp --trustAll --set enabled:true --no-prompt
echo "-- Done"
echo ""
echo "Creating Password Policy"
echo "------------------------"
echo "-> Creating Password Validators"
echo ""
tmpStr1="9 Characters"
echo "-- Creating validator (${tmpStr1})"
${DS_APP}/bin/dsconfig create-password-validator --hostname "${svcURL_curr}" --port ${adminConnectorPort} \
 --bindDN "${rootUserDN}" --bindPassword "${rootUserPassword}" --validator-name "${tmpStr1}" --type length-based \
 --set enabled:true --set min-password-length:9 --trustAll --no-prompt
echo "-- Done"
echo ""
tmpStr2="Weak Passwords"
echo "-- Creating validator (${tmpStr2})"
${DS_APP}/bin/dsconfig create-password-validator --hostname "${svcURL_curr}" --port ${adminConnectorPort} \
  --bindDN "${rootUserDN}" --bindPassword "${rootUserPassword}" --validator-name "${tmpStr2}" --type dictionary \
  --set enabled:true --set dictionary-file:config/common-passwords.txt --set case-sensitive-validation:true \
  --set test-reversed-password:false --trustAll --no-prompt
echo "-- Done"
echo ""
tmpStr3="Valid Passwords Characters"
echo "-- Creating validator (${tmpStr3})"
${DS_APP}/bin/dsconfig create-password-validator --hostname "${svcURL_curr}" --port ${adminConnectorPort} \
  --bindDN "${rootUserDN}" --bindPassword "${rootUserPassword}" --validator-name "${tmpStr3}" --type character-set \
  --set allow-unclassified-characters:true --set enabled:true \
  --set character-set:0:abcdefghijklmnopqrstuvwxyz \
  --set character-set:0:ABCDEFGHIJKLMNOPQRSTUVWXYZ \
  --set character-set:0:0123456789 \
  --set character-set:0:\!\"\#\$%\&\'\(\)\*+\,-./:\;\\\<=\>\?@\[\]\^_\`\{\|\}~ \
  --set min-character-sets:3 \
 --trustAll \
 --no-prompt
echo "-> Updating default password policy to:"
echo "   : password-history-count is 3"
echo "   : minimum-password-length is 9"
echo "   : lowercase characters (a through z)"
echo "   : uppercase characters (A through Z)"
echo "   : Base 10 digits (0 through 9)"
echo "   : Non-alphabetic characters (for example, !, \$, #, %)"
${DS_APP}/bin/dsconfig set-password-policy-prop --hostname "${svcURL_curr}" --port ${adminConnectorPort} \
  --bindDN "${rootUserDN}" --bindPassword "${rootUserPassword}" --policy-name "Default Password Policy" \
  --set password-history-count:3 \
  --set password-validator:"${tmpStr1}" \
  --set password-validator:"${tmpStr2}" \
  --set password-validator:"${tmpStr3}" \
  --trustAll \
  --no-prompt
echo "-- Done"
echo ""
