#
# Legal Notice: Installation and use of this script is subject to 
# a license agreement with Midships Limited (a company registered 
# in England, under company registration number: 11324587).
# This script cannot be modified or shared with another organisation 
# unless approved in writing by Midships Limited.
# You as a user of this script must review, accept and comply with the 
# license terms of each downloaded/installed package that is referenced 
# by this script. By proceeding with the installation, you are accepting 
# the license terms of each package, and acknowledging that your use of 
# each package will be subject to its respective license terms.
#=======================================================================
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.am.service_name }}-lb"
  namespace: {{ .Values.am.namespace }}
  labels:
    app: {{ .Values.am.pod_name | quote }}
    release: {{ .Values.am.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.am.pod_name | quote }}
  ports:
  - name: httpsam
    port: 8443
    targetPort: 8443
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.am.service_name | quote }}
  namespace: {{ .Values.am.namespace }}
  labels:
    app: {{ .Values.am.pod_name | quote }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.am.pod_name | quote }}
  ports:
  - name: ldapcs
    port: 1390
    targetPort: 1390
    protocol: TCP
  - name: ldapscs
    port: 1637
    targetPort: 1637
    protocol: TCP
  - name: httpcs
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: httpsam
    port: 8443
    targetPort: 8443
    protocol: TCP
  - name: httpscs
    port: 8444
    targetPort: 8444
    protocol: TCP
  - name: admincs
    port: 4445
    targetPort: 4445
    protocol: TCP
  - name: replication
    port: 8989
    targetPort: 8989
    protocol: TCP
