#
# Legal Notice: Installation and use of this script is subject to 
# a license agreement with Midships Limited (a company registered 
# in England, under company registration number: 11324587).
# This script cannot be modified or shared with another organisation 
# unless approved in writing by Midships Limited.
# You as a user of this script must review, accept and comply with the 
# license terms of each downloaded/installed package that is referenced 
# by this script. By proceeding with the installation, you are accepting 
# the license terms of each package, and acknowledging that your use of 
# each package will be subject to its respective license terms.
#=======================================================================
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.replserver.pod_name | quote }}
  # Should NOT include digits
  namespace: {{ .Values.replserver.namespace | quote }}
spec:
  serviceName: {{ .Values.replserver.service_name | quote }}
  replicas: {{ .Values.replserver.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.replserver.pod_name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.replserver.pod_name | quote }}
    spec:
      hostAliases:
        {{- if and .Values.replserver.hostAliases_ip1 .Values.replserver.hostAliases_hostname1 }}
        - ip: {{ .Values.replserver.hostAliases_ip1 | quote }}
          hostnames:
          - {{ .Values.replserver.hostAliases_hostname1 | quote }}
        # Only use when public loadbalacer does not have a domain name
        {{- end }}
        {{- if and .Values.replserver.hostAliases_ip2 .Values.replserver.hostAliases_hostname2 }}
        - ip: {{ .Values.replserver.hostAliases_ip2 | quote }}
          hostnames:
          - {{ .Values.replserver.hostAliases_hostname2 | quote }}
          # Only use when public IP for this server does not have a domain name
        {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - {{ .Values.replserver.pod_name | quote }}
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsUser: 10002
        runAsGroup: 10002
        fsGroup: 10002
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: pvc
        - name: tmp
          emptyDir: {}
        - name: java-truststore
          emptyDir: {}
        {{- if eq (lower .Values.replserver.secrets_mode | quote) ("k8s" | quote) }}
        - name: configmaps-rs
          configMap:
            name: {{ .Values.replserver.pod_name | quote }}
        - name: secrets-rs
          secret:
            secretName: {{ .Values.replserver.pod_name | quote }}
        - name: secrets-us
          secret:
            secretName: {{ .Values.userstore.pod_name | quote }}
        - name: secrets-ts
          secret:
            secretName: {{ .Values.tokenstore.pod_name | quote }}
        - name: secrets-cs
          secret:
            secretName: {{ .Values.configstore.pod_name | quote }}
        {{- end }}
      containers:
      - name: {{ .Values.replserver.pod_name | quote }}
        image: {{ .Values.replserver.image | quote }}
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/opt/ds/app"
            name: pvc
          - mountPath: "/tmp"
            name: tmp
          - mountPath: /etc/pki/ca-trust/extracted/java
            name: java-truststore
          {{- if eq (lower .Values.replserver.secrets_mode | quote) ("k8s" | quote) }}
          - name: configmaps-rs
            mountPath: /opt/ds/configmaps # do NOT change
          - name: secrets-rs
            mountPath: /opt/ds/secrets # do NOT change
          - name: secrets-cs
            mountPath: /opt/cs/secrets # do NOT change
          - name: secrets-us
            mountPath: /opt/us/secrets # do NOT change
          - name: secrets-ts
            mountPath: /opt/ts/secrets # do NOT change
          {{- end }}
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 1Gi
        readinessProbe:
          httpGet:
            port: 8443
            path: /alive
            scheme: HTTPS
          initialDelaySeconds: 120 # how long to wait before checking
          periodSeconds: 15 # how long to wait between checks
          successThreshold: 2 # how many successes to hit before accepting
          failureThreshold: 10 # how many failures to accept before failing
          timeoutSeconds: 5 # how long to wait for a response
        env:
          - name: POD_BASENAME
            value: {{ .Values.replserver.pod_name | quote }}
            # Copy from metadata.name
          - name: "POD_SERVICE_NAME"
            value: {{ .Values.replserver.service_name | quote }}
            # Copy of metadata.name from the service.yml for this pod
          - name: CLUSTER_DOMAIN
            value: {{ .Values.replserver.cluster_domain | quote }}
            # Kubernetes cluster domain
          - name: POD_REPLICAS
            value: {{ .Values.replserver.replicas | quote }}
            # Copy from spec.replicas
          - name: BASEDN_TO_REPL_US
            value: {{ .Values.replserver.basedn_to_repl_us | quote }}
            # The user store base DN to replicate. E.g. "ou=users"
          - name: BASEDN_TO_REPL_TS
            value: {{ .Values.replserver.basedn_to_repl_ts | quote }}
            # The token store base DN to replicate. E.g. "ou=tokens"
          - name: BASEDN_TO_REPL_CS
            value: {{ .Values.replserver.basedn_to_repl_cs | quote }}
            # The token store base DN to replicate. E.g. "ou=am-config"
          - name: SRVs_TO_REPL_US
            value: {{ .Values.replserver.srvs_to_repl_us | quote }}
            # Comma separated User Store K8s SVC url. E.g. {hostname}.{service-name}.{POD_NAMESPACE}.svc.cluster.local,{hostname}.{service-name}.{POD_NAMESPACE}.svc.cluster.local
          - name: SRVs_TO_REPL_TS
            value: {{ .Values.replserver.srvs_to_repl_ts | quote }}
            # Comma separated Token Store K8s SVC url. E.g. {hostname}.{service-name}.{POD_NAMESPACE}.svc.cluster.local,{hostname}.{service-name}.{POD_NAMESPACE}.svc.cluster.local
          - name: SRVs_TO_REPL_CS
            value: {{ .Values.replserver.srvs_to_repl_cs | quote }}
            # Comma separated Config Store K8s SVC url. E.g. {hostname}.{service-name}.{POD_NAMESPACE}.svc.cluster.local,{hostname}.{service-name}.{POD_NAMESPACE}.svc.cluster.local
          - name: ENV_TYPE
            value: {{ .Values.replserver.env_type | quote }}
            # Recommended vaules are SIT, UAT, NFT, PRE_PROD, PROD
          - name: USE_CUSTOM_JAVA_PROPS
            value: {{ .Values.replserver.use_javaProps | quote }}
            # Use of external file for loading java properties. Acccepted values 'true' or 'false'
          - name: GLOBAL_REPL_ON
            value: {{ .Values.replserver.global_repl_on | quote }}
            # Turn on Global Replication (Across Regions / Cloud Providers / Clusters). E.g. true or false
          - name: GLOBAL_REPL_FQDNS
            value: {{ .Values.replserver.global_repl_fqdns | quote }}
            # Comma separated Replication Server domains in another Region / Cloud Provider / Cluster to replication to.
            # Only used when GLOBAL_REPL_ON is set to 'true'.
          - name: SECRETS_MODE
            value: {{ .Values.replserver.secrets_mode | default "k8s" | quote }}
            # Accepted values 'k8s' or 'REST'. Former where secrets and config are stored in K8s, later in a REST secrets manager.
          - name: VAULT_BASE_URL
            value: {{ .Values.vault.url | quote }}
          - name: VAULT_TOKEN
            value: {{ .Values.vault.token | quote }}
          - name: VAULT_CLIENT_PATH_RS
            value: {{ .Values.vault.rs_path | quote }}
          - name: VAULT_CLIENT_PATH_TS
            value: {{ .Values.vault.ts_path | quote }}
          - name: VAULT_CLIENT_PATH_US
            value: {{ .Values.vault.us_path | quote }}
          - name: VAULT_CLIENT_PATH_CS
            value: {{ .Values.vault.cs_path | quote }}
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
            # The namespace of this pod and the user/token store pods to be replicated
        ports:
          - name: ldaps
            containerPort: 1636
            protocol: TCP
          - name: admin
            containerPort: 4444
            protocol: TCP
          - name: replication
            containerPort: 8989
            protocol: TCP
          - name: https
            containerPort: 8443
            protocol: TCP
      imagePullSecrets:
      - name: fr-nexus-docker
  volumeClaimTemplates:
    - metadata:
        name: pvc
        annotations:
          pv.beta.kubernetes.io/gid: "0"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
