#
# Legal Notice: Installation and use of this script is subject to 
# a license agreement with Midships Limited (a company registered 
# in England, under company registration number: 11324587).
# This script cannot be modified or shared with another organisation 
# unless approved in writing by Midships Limited.
# You as a user of this script must review, accept and comply with the 
# license terms of each downloaded/installed package that is referenced 
# by this script. By proceeding with the installation, you are accepting 
# the license terms of each package, and acknowledging that your use of 
# each package will be subject to its respective license terms.
#=======================================================================
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configstore.pod_name | default "forgerock-config-store" | quote }}
  namespace: {{ .Values.configstore.namespace | quote }}
type: Opaque
stringData:
  amConfigAdminPassword: {{ .Values.configstore.amConfigAdminPassword }}
  configStoreCertPwd: {{ .Values.configstore.configStoreCertPwd }}
  deploymentKey: {{ .Values.configstore.deploymentKey }}
  monitorUserPassword: {{ .Values.configstore.monitorUserPassword }}
  rootUserPassword: {{ .Values.configstore.rootUserPassword }}
  truststorePwd: {{ .Values.configstore.truststorePwd }}
  certificate: |-
    {{- .Values.configstore.certificate | nindent 4 }}
  certificateKey: |
    {{- .Values.configstore.certificateKey | nindent 4 }}
