#
# Legal Notice: Installation and use of this script is subject to 
# a license agreement with Midships Limited (a company registered 
# in England, under company registration number: 11324587).
# This script cannot be modified or shared with another organisation 
# unless approved in writing by Midships Limited.
# You as a user of this script must review, accept and comply with the 
# license terms of each downloaded/installed package that is referenced 
# by this script. By proceeding with the installation, you are accepting 
# the license terms of each package, and acknowledging that your use of 
# each package will be subject to its respective license terms.
#=======================================================================
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.am.pod_name | default "forgerock-access-manager" | quote }}
  namespace: {{ .Values.secrets.namespace | quote }}
type: Opaque
stringData:
  amAdminPwd: {{ .Values.am.amAdminPwd }}
  cfgStoreDirMgrPwd: {{ .Values.am.cfgStoreDirMgrPwd }}
  ctsDirMgrPwd: {{ .Values.am.ctsDirMgrPwd }}
  tomcatJKSPwd: {{ .Values.am.tomcatJKSPwd }}
  truststorePwd: {{ .Values.am.truststorePwd }}
  userStoreDirMgrPwd: {{ .Values.am.userStoreDirMgrPwd }}
  encKey_AmPwd: {{ .Values.am.encKey_AmPwd }}
  encKey_directenc: {{ .Values.am.encKey_directenc }}
  encKey_hmacsign: {{ .Values.am.encKey_hmacsign }}
  encKey_selfservicesign: {{ .Values.am.encKey_selfservicesign }}
  cert_es256: |-
    {{- .Values.am.cert_es256 | nindent 4 }}
  cert_es256Key: |-
    {{- .Values.am.cert_es256Key | nindent 4 }}
  cert_es384: |-
    {{- .Values.am.cert_es384 | nindent 4 }}
  cert_es384Key: |-
    {{- .Values.am.cert_es384Key | nindent 4 }}
  cert_es512: |-
    {{- .Values.am.cert_es512 | nindent 4 }}
  cert_es512Key: |-
    {{- .Values.am.cert_es512Key | nindent 4 }}
  cert_general: |-
    {{- .Values.am.cert_general | nindent 4 }}
  cert_generalKey: |-
    {{- .Values.am.cert_generalKey | nindent 4 }}
  cert_rsajwtsign: |-
    {{- .Values.am.cert_rsajwtsign | nindent 4 }}
  cert_rsajwtsignKey: |-
    {{- .Values.am.cert_rsajwtsignKey | nindent 4 }}
  cert_selfserviceenc: |-
    {{- .Values.am.cert_selfserviceenc | nindent 4 }}
  cert_selfserviceencKey: |-
    {{- .Values.am.cert_selfserviceencKey | nindent 4 }}
  certificate: |-
    {{- .Values.am.certificate | nindent 4 }}
  certificateKey: |
    {{- .Values.am.certificateKey | nindent 4 }}
